### ISSUE TITLE
disabling extensions makes all private discussions public

### ISSUE THREAD

**Issue by luceos** [flagrow/byobu#11]
We need to allow for webmasters to hide all private discussions once the extension is disabled. You might be doing this accidentally or as a requirement for an upgrade of the core.

There are several ways of doing this, one might be to create a temporary tag and assign all private discussions to that. But this relies heavily on the tags extension. Another way might be to set the deleted_at property of the discussion and remember on disk which discussion id's were hidden.

**Comment by jordanjay29** [comment]
You could record the hide time somewhere and restore all discussions with that value.

**Comment by Luceos** [comment]
Hm, yes that hide_time might be a good solution.

**Comment by Magicalex** [comment]
Why not store messages in other table?

**Comment by Luceos** [comment]
Hello @Magicalex thanks for joining the discussion. A few reasons exist for this set up;

- I strongly believe in short iterative development cycles. Keeping required work within a short scope makes it more manageable to finish. The fastest way of accomplishing private discussions was by re-using as much as possible, not creating a new table. Even so the implementation is and has been quite complex anyway.
- The whole discussion about private messaging versus private discussions has been going for a while now. Toby (or replace with Flarum if you need) never decided for the obvious way of implementation, but for the most flexible. In my opinion private messaging in fact still ís private discussions. You have two or more people joining together in a private discussion thread. 
- Re-using the existing table and existing functionality, allows us to benefit from other logic (eg flagging, tagging etc) without re-inventing the wheel, it also allows for easier extendability.

**Comment by Magicalex** [comment]
Ok, i'm agree with your opinion (private messaging vs private discussion).

My question is: how to store private discussions in the database.
If we mix private discussions and forum discussions in the database, I don't see any lightening solution to hide messages after the extension is disabled (refer to `hide_time`).
You can always re-use the elements of flarum without re-using the existing tables? (well I think?)

Off topic: mixing tags with private discussions can lead users to confusion (this is my opinion).

**Comment by Luceos** [comment]
@Magicalex I think mixing tags with PD's will open a world of possibilities ;)

Re-using the logic but not the tables will not work, because the models are very tightly coupled with the code and the js. If I split the tables up I'll have to reimplement everything from core, which will be hard to maintain.

**Comment by tobscure** [comment]
Excuse me for butting in on this thread, but...

Using `hide_time` won't work because then what will happen to deleted private discussions after you re-enable the extension? They'll be un-deleted.

No, I think we will add something to core to make this possible.

We'll add a new boolean column to the discussions table called `private`. Not in the sense of "this is a byobu private discussion", but rather meaning "this discussion should be hidden from the public, until some extension comes along and explicitly grants users permission". Kind of like an inversion of the default permissions. And we'll add a similar column on the posts table — though it won't be used here, it will be useful if someone wants to build a "Whispers" extension or similar.

How does that sound?

**Comment by Luceos** [comment]
That might be a good idea. The private on a post could also allow for private EventPosts with a custom message when a certain post was deleted to be shown only to the author of the removed post.

**Comment by tobscure** [comment]
Great, feel free to submit a PR to core for this in the short-term if you want (for a beta 7 release?), otherwise I'll add it to the API spec.
