### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by luceos** [flagrow/byobu#45]
@pflstr from #5 

In my opinion, there are several questions to be answered.

a) Who can add or remove recipients of a private conversation? If it's only the admin it's quite easy, we just need to add a special case for a recipient wanting to leave a private discussion. This right will be given in addition to the right of the admin.

b) If the right to add and remove recipients of a private conversation is given to non-staff usergroups as well, one should be aware, that a breach of confidence might result, if posts older than the time of the change of recipients become accessible to new recipients. This needs to be avoided to protect a forum owner from legal implications. The right to leave such a discussion voluntarily would apply in this case as well.

c) If users are allowed to leave and reenter a private discussion, we may need more than one entry date and / or more than one leave date. The database query to filter out the posts that should be shown to such a user may become quite complex. What should be done with quotes from posts, that are not supposed to be shown to a certain user?

My suggestion: Don't let the list of recipients be altered after the start of a private discussion: The only exception should the case of a user leaving such a discussion voluntarily. Even in this case one should favor a solution, where the given recipient is not removed from the list but instead the discussion can be ignored by any recipient (and the ignoring can be revoked without legal consequences, because the user never really left).

If participants of a private discussion want to expell a certain user, they can simply start a new discussion without the given user.

One last question remains:

d) Who should have the right to close a private discussion? The original poster? Any participant? And who should have the right to reopen a closed discussion?

**Comment by luceos** [comment]
a) these are permission based per tag, check your permission tab in the admin
b) right to leave certainly applies, how permissions are set up is completely up to the owner of the forum, for leaving a discussion see #5 
c) users are either removed or they are not, we will not track when they have been added or removed, they are either added and added+removed. See #5 

---

Related to your suggestion. It's up to the admin how he configures the permissions, if he wants to reject editing recipients he can do so using the permissions. There's no need for the package maintainer to decide how the extension is used as scenarios are different in extremities.

d) Closing a discussion is up to the permission group with the close permission. How that is implemented is up to the user.

---

Thanks for your questions. Please understand as a package maintainer we don't want to enforce how you use the extension. The actual use differs per forum and its type. We always aim to keep our extensions as flexible as possible.

**Comment by pflstr** [comment]
Thank you for turning my post into a new issue.

> c) users are either removed or they are not, we will not track when they have been added or removed, they are either added and added+removed.

My thoughts were related to the suggestion of  jordanjay29 (original post in [#5](https://github.com/flagrow/byobu/issues/5): "Could they retain a copy of the messages thus far?"). If you don't intend to follow this route, things will be much easier and my question in this regard obsolete.

> There's no need for the package maintainer to decide how the extension is used as scenarios are different in extremities.

I absolutely agree and I really appreciate your efforts to provide these freedoms. I just wanted to point to possible pitfalls I envision in certain usecases. But like you said, in the end it's the responsibility of a forum owner to decide how he or she wants to setup the extension.

> d) Closing a discussion is up to the permission group with the close permission. How that is implemented is up to the user.

I know these settings. When it comes to private discussions that are often not accessible to mods and admins, the given permission group however isn't as useful as it is in other circumstances.

Not restricted to and not part of your extension: It would be nice to have the original poster as a pseudo usergroup, so that the permission to close a discussion or to change the recipients could be granted to the OP. What do you think?

**Comment by luceos** [comment]
> When it comes to private discussions that are often not accessible to mods and admins, the given permission group however isn't as useful as it is in other circumstances.

This is indeed something to consider. And your suggestion of allowing the OP to close a discussion too.
